INSERT INTO dim_users
(
    UserID,
    Person,
    CurrentAge,
    RetirementAge,
    BirthYear,
    BirthMonth,
    Gender,
    Address,
    Apartment,
    City,
    State,
    Zipcode,
    Latitude,
    Longitude,
    PerCapitaIncome,
    YearlyIncome,
    TotalDebt,
    FICOScore,
    NumCreditCards,
    AgeGroup,
    FICOCategory,
    DebtToIncomeRatio,
    IncomeGroup
)
SELECT
    [User],
    Person,
    [Current Age],
    [Retirement Age],
    [Birth Year],
    [Birth Month],
    Gender,
    Address,
    CAST(Apartment AS INT),
    City,
    State,
    Zipcode,
    CAST(Latitude AS DECIMAL(9,6)),
    CAST(Longitude AS DECIMAL(9,6)),
    CAST([Per Capita Income - Zipcode] AS DECIMAL(18,2)),
    CAST([Yearly Income - Person] AS DECIMAL(18,2)),
    CAST([Total Debt] AS DECIMAL(18,2)),
    [FICO Score],
    [Num Credit Cards],
    [Age Group],
    [FICO Category],
    CAST([Debt to Income Ratio] AS DECIMAL(10,2)),
    [Income Group]
FROM stg_users;